# Generated by Django 2.1.3 on 2018-12-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muvekkil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DavaKarsiTaraf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davakarsitaraf_isim', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dava',
            options={'ordering': ('-dava_start',), 'verbose_name': 'dava', 'verbose_name_plural': 'davalar'},
        ),
        migrations.AlterModelOptions(
            name='surec',
            options={'ordering': ('-surec_date',), 'verbose_name': 'Dava Süreci', 'verbose_name_plural': 'Dava Süreçleri'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Müvekkil', 'verbose_name_plural': 'Müvekkiller'},
        ),
        migrations.AddField(
            model_name='dava',
            name='dava_category',
            field=models.CharField(choices=[('Adli', 'Adli'), ('Ceza', 'Ceza'), ('İdari', 'İdari'), ('Tahkim', 'Tahkim'), ('Arabuluculuk', 'Arabuluculuk')], default='Kategori Belirtilmemiş', max_length=30, verbose_name='Dava Kategorisi'),
        ),
        migrations.AddField(
            model_name='dava',
            name='dava_esasno',
            field=models.CharField(default='', max_length=150, verbose_name='Dava Esas Numarası'),
        ),
        migrations.AlterField(
            model_name='dava',
            name='dava_description',
            field=models.TextField(verbose_name='Dava Açıklaması'),
        ),
        migrations.AlterField(
            model_name='dava',
            name='dava_link',
            field=models.CharField(max_length=300, verbose_name='Dava Dosyalarının Olduğu Link'),
        ),
        migrations.AlterField(
            model_name='dava',
            name='dava_title',
            field=models.CharField(max_length=150, verbose_name='Dava Adı'),
        ),
        migrations.AlterField(
            model_name='surec',
            name='surec_date',
            field=models.DateField(verbose_name='Süreç Zamanı'),
        ),
        migrations.AlterField(
            model_name='surec',
            name='surec_description',
            field=models.TextField(verbose_name='Süreç Açıklaması'),
        ),
        migrations.AlterField(
            model_name='surec',
            name='surec_title',
            field=models.CharField(max_length=150, verbose_name='Süreç Başlığı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Müvekkil Email'),
        ),
        migrations.AddField(
            model_name='dava',
            name='davakarsitaraf',
            field=models.ManyToManyField(to='muvekkil.DavaKarsiTaraf'),
        ),
    ]
