# Generated by Django 2.1.3 on 2018-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muvekkil', '0002_auto_20181219_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='davakarsitaraf',
            options={'ordering': ('davakarsitaraf_isim',), 'verbose_name': 'Dava Karşı Taraf', 'verbose_name_plural': 'Dava Karşı Tarafları'},
        ),
        migrations.AddField(
            model_name='dava',
            name='dava_mahkeme',
            field=models.CharField(choices=[('Asliye Hukuk Mahkemesi', 'Asliye Hukuk Mahkemesi'), ('Sulh Hukuk Mahkemesi', 'Sulh Hukuk Mahkemesi'), ('Aile Mahkemesi', 'Aile Mahkemesi'), ('İş Mahkemesi', 'İş Mahkemesi'), ('Ticaret Mahkemesi', 'Ticaret Mahkemesi'), ('İcra Mahkemesi', 'İcra Mahkemesi'), ('Tüketici Mahkemesi', 'Tüketici Mahkemesi'), ('Sulh Ceza Mahkemesi', 'Sulh Ceza Mahkemesi'), ('Asliye Ceza Mahkemesi', 'Asliye Ceza Mahkemesi'), ('Ağır Ceza Mahkemesi', 'Ağır Ceza Mahkemesi'), ('İcra Dairesi', 'İcra Dairesi'), ('İdare Mahkemesi', 'İdare Mahkemesi'), ('Vergi Mahkemesi', 'Vergi Mahkemesi')], default='', max_length=50, verbose_name='Davanın Görüldüğü Mahkeme'),
        ),
        migrations.AddField(
            model_name='dava',
            name='dava_mahkemeonad',
            field=models.CharField(default='', max_length=50, verbose_name='Mahkeme Adliye ve Numarası'),
        ),
        migrations.AddField(
            model_name='dava',
            name='dava_sifat',
            field=models.CharField(choices=[('Davacı', 'Davacı'), ('Davalı', 'Davalı')], default='', max_length=50, verbose_name='Davadaki Sıfatımız'),
        ),
    ]
