# Generated by Django 2.1.3 on 2019-01-19 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muvekkil', '0003_auto_20181220_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosyalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_adi', models.CharField(max_length=60, verbose_name='Dosya Adı: ')),
                ('dosya_aciklamasi', models.CharField(max_length=150, verbose_name='Dosya Açıklaması: ')),
                ('dosya_dosyasi', models.FileField(upload_to='', verbose_name='Gelen Dosya: ')),
                ('dosya_gonderilme_tarihi', models.DateField(auto_now_add=True, verbose_name='Gönderilme Tarihi')),
                ('dava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muvekkil.Dava')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gönderilen Dosya',
                'verbose_name_plural': 'Gönderilen Dosyalar',
                'ordering': ('-dosya_gonderilme_tarihi',),
            },
        ),
    ]
